from PIL import Image
image = Image.open('images/원료통1_부스터.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통1_부스터_resize.png')
image = Image.open('images/원료통2_WPC.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통2_WPC_resize.png')
image = Image.open('images/원료통3_WPI.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통3_WPI_resize.png')
image = Image.open('images/원료통4_비건.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통4_비건_resize.png')
image = Image.open('images/원료통5_게이너.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통5_게이너_resize.png')
image = Image.open('images/원료통6_BCAA.png')
resize_image = image.resize((300,400))
resize_image.save('images/원료통6_BCAA_resize.png')


